package com.arsvie.pocketharness.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * The four looks. Every color here is chosen deliberately; the palettes are:
 *  - GINGERBREAD: warm-grey Android 2.x chrome, olive-green accent, glossy buttons.
 *  - MINIMAL:     #FAFAF9 paper, ink-black actions, functional status colors only.
 *  - TOMORROW:    4chan "Tomorrow" — exact tokens from s.4cdn.org/css/tomorrow.css
 *                 (the palette the manga-translation pipeline already uses).
 *  - STUDIO:      beautifului.dev tokens (oklch values converted to sRGB): canvas #F1F2F3,
 *                 accent #0285FF, ink #1F2124, green #199A4D, orange #EF720D, red #E3474C.
 */

val GingerbreadTheme = PhTheme(
    id = PhLook.GINGERBREAD,
    name = "Gingerbread",
    blurb = "2010-era Android chrome, skeuomorphic — the original look, rebuilt",
    dark = false,
    colors = PhColors(
        bg = Color(0xFFEAE8E3),
        surface = Color(0xFFFBFAF7),
        surfaceAlt = Color(0xFFF2F0EB),
        hairline = Color(0xFFD6D2C9),
        border = Color(0xFFBFBAB0),
        borderStrong = Color(0xFF8F8A80),
        text = Color(0xFF24221E),
        textDim = Color(0xFF6B665E),
        textFaint = Color(0xFF99948A),
        heading = Color(0xFF4A463E),
        note = Color(0xFF6B665E),
        accent = Color(0xFF5C8A2A),
        accentText = Color(0xFFFFFFFF),
        accentTint = Color(0xFFE7EFDC),
        link = Color(0xFF3A6EA5),
        ok = Color(0xFF4E8A3C),
        warn = Color(0xFFC07F1F),
        err = Color(0xFFB23B3B),
        run = Color(0xFFB08A1E),
        userBg = Color(0xFFD9E4EE),
        userText = Color(0xFF1E2A35),
        agentBg = Color(0xFFFCFBF8),
        agentText = Color(0xFF24221E),
        thinkBg = Color(0xFFF6EFD8),
        thinkText = Color(0xFF6A5B22),
        thinkLine = Color(0xFFDDD2AE),
        codeBg = Color(0xFF121212),
        codeText = Color(0xFFC8E6C8),
        codeErr = Color(0xFFF0A6A6),
        errTint = Color(0xFFF6E3E3),
        warnTint = Color(0xFFF8ECD6),
        barTop = Color(0xFF7B7B7B),
        barBottom = Color(0xFF3F3F3F),
        onBar = Color(0xFFFFFFFF),
        onBarDim = Color(0xFFD8D8D8),
    ),
    shape = PhShape(card = 6.dp, small = 4.dp, chip = 5.dp, status = 2.dp),
    type = PhType(
        title = 17.sp,
        body = 14.5.sp,
        meta = 12.sp,
        mono = 12.5.sp,
        titleWeight = FontWeight.Bold,
        titleSpacing = 0.sp,
        emboss = true,
    ),
    bar = PhBar.GRADIENT,
    card = PhCard.BEVEL,
    button = PhButton.GLOSS,
    message = PhMessage.BUBBLE_BEVEL,
    mono = PhMono.TERMINAL,
    header = PhHeader.BAND,
)

val MinimalTheme = PhTheme(
    id = PhLook.MINIMAL,
    name = "Minimal",
    blurb = "De-slopped modern light — neutral, one accent, no decoration",
    dark = false,
    colors = PhColors(
        bg = Color(0xFFFAFAF9),
        surface = Color(0xFFFFFFFF),
        surfaceAlt = Color(0xFFF5F5F3),
        hairline = Color(0xFFE8E8E5),
        border = Color(0xFFDEDED9),
        borderStrong = Color(0xFFC9C9C2),
        text = Color(0xFF17181A),
        textDim = Color(0xFF5D5F63),
        textFaint = Color(0xFF8E9095),
        heading = Color(0xFF5D5F63),
        note = Color(0xFF5D5F63),
        accent = Color(0xFF1A1A1A),
        accentText = Color(0xFFFFFFFF),
        accentTint = Color(0xFFEFEFEC),
        link = Color(0xFF2F5FA8),
        ok = Color(0xFF2E7D4F),
        warn = Color(0xFFA9761C),
        err = Color(0xFFB23B3B),
        run = Color(0xFF5B6470),
        userBg = Color(0xFFF0F0EE),
        userText = Color(0xFF17181A),
        agentBg = Color(0xFFFFFFFF),
        agentText = Color(0xFF17181A),
        thinkBg = Color(0xFFF5F5F3),
        thinkText = Color(0xFF5D5F63),
        thinkLine = Color(0xFFE3E3DF),
        codeBg = Color(0xFFF4F4F2),
        codeText = Color(0xFF33353A),
        codeErr = Color(0xFFA33B3B),
        errTint = Color(0xFFF7E9E9),
        warnTint = Color(0xFFF7EFDD),
        barTop = Color(0xFFFAFAF9),
        barBottom = Color(0xFFFAFAF9),
        onBar = Color(0xFF17181A),
        onBarDim = Color(0xFF5D5F63),
    ),
    shape = PhShape(card = 10.dp, small = 8.dp, chip = 6.dp, status = 2.dp),
    type = PhType(
        title = 20.sp,
        body = 14.5.sp,
        meta = 12.sp,
        mono = 12.5.sp,
        titleWeight = FontWeight.SemiBold,
        titleSpacing = 0.sp,
        emboss = false,
    ),
    bar = PhBar.FLAT,
    card = PhCard.HAIRLINE,
    button = PhButton.SOLID,
    message = PhMessage.BUBBLE_FLAT,
    mono = PhMono.INSET_LIGHT,
    header = PhHeader.CAPS,
)

val TomorrowTheme = PhTheme(
    id = PhLook.TOMORROW,
    name = "Tomorrow",
    blurb = "4chan board dark — the manga-pipeline palette, dense and flat",
    dark = true,
    colors = PhColors(
        bg = Color(0xFF1D1F21),
        surface = Color(0xFF282A2E),
        surfaceAlt = Color(0xFF1D1F21),
        hairline = Color(0xFF282A2E),
        border = Color(0xFF3A3D42),
        borderStrong = Color(0xFF111111),
        text = Color(0xFFC5C8C6),
        textDim = Color(0xFF969896),
        textFaint = Color(0xFF6B6F74),
        heading = Color(0xFFB294BB),
        note = Color(0xFF8ABEB7),
        accent = Color(0xFF81A2BE),
        accentText = Color(0xFF1D1F21),
        accentTint = Color(0xFF2D343A),
        link = Color(0xFF81A2BE),
        ok = Color(0xFFB5BD68),
        warn = Color(0xFFDE935F),
        err = Color(0xFFCC6666),
        run = Color(0xFFF0C674),
        userBg = Color(0xFF282A2E),
        userText = Color(0xFFC5C8C6),
        agentBg = Color(0xFF282A2E),
        agentText = Color(0xFFC5C8C6),
        thinkBg = Color(0xFF000000),
        thinkText = Color(0xFFC5C8C6),
        thinkLine = Color(0xFF3A3D42),
        codeBg = Color(0xFF1D1F21),
        codeText = Color(0xFFC5C8C6),
        codeErr = Color(0xFFCC6666),
        errTint = Color(0xFF33272A),
        warnTint = Color(0xFF3A3428),
        barTop = Color(0xFF1D1F21),
        barBottom = Color(0xFF1D1F21),
        onBar = Color(0xFFC5C8C6),
        onBarDim = Color(0xFF969896),
    ),
    shape = PhShape(card = 2.dp, small = 2.dp, chip = 2.dp, status = 1.dp),
    type = PhType(
        title = 21.sp,
        body = 13.5.sp,
        meta = 11.5.sp,
        mono = 12.5.sp,
        titleWeight = FontWeight.Bold,
        titleSpacing = (-0.5).sp,
        emboss = false,
    ),
    bar = PhBar.BANNER,
    card = PhCard.FILLED,
    button = PhButton.BOARD,
    message = PhMessage.POST,
    mono = PhMono.BOARD_DARK,
    header = PhHeader.LEGEND,
)

val StudioTheme = PhTheme(
    id = PhLook.STUDIO,
    name = "Studio",
    blurb = "AI-native primitives — crafted chips, traces, soft surfaces",
    dark = false,
    colors = PhColors(
        bg = Color(0xFFF1F2F3),
        surface = Color(0xFFFFFFFF),
        surfaceAlt = Color(0xFFF7F8F9),
        hairline = Color(0xFFECEDEF),
        border = Color(0xFFE0E2E5),
        borderStrong = Color(0xFFCDD0D5),
        text = Color(0xFF1F2124),
        textDim = Color(0xFF62656B),
        textFaint = Color(0xFF9A9DA3),
        heading = Color(0xFF62656B),
        note = Color(0xFF62656B),
        accent = Color(0xFF0285FF),
        accentText = Color(0xFFFFFFFF),
        accentTint = Color(0xFFE9F3FF),
        link = Color(0xFF0070DD),
        ok = Color(0xFF199A4D),
        warn = Color(0xFFEF720D),
        err = Color(0xFFE3474C),
        run = Color(0xFF0285FF),
        userBg = Color(0xFFE9F3FF),
        userText = Color(0xFF0B3F7A),
        agentBg = Color(0xFFFFFFFF),
        agentText = Color(0xFF1F2124),
        thinkBg = Color(0xFFF7F8F9),
        thinkText = Color(0xFF62656B),
        thinkLine = Color(0xFFECEDEF),
        codeBg = Color(0xFFF4F5F6),
        codeText = Color(0xFF3A3D42),
        codeErr = Color(0xFFC43D42),
        errTint = Color(0xFFFCECEC),
        warnTint = Color(0xFFFDF1E5),
        barTop = Color(0xFFFFFFFF),
        barBottom = Color(0xFFFFFFFF),
        onBar = Color(0xFF1F2124),
        onBarDim = Color(0xFF62656B),
    ),
    shape = PhShape(card = 12.dp, small = 10.dp, chip = 8.dp, status = 3.dp),
    type = PhType(
        title = 18.sp,
        body = 14.5.sp,
        meta = 11.5.sp,
        mono = 12.5.sp,
        titleWeight = FontWeight.SemiBold,
        titleSpacing = 0.sp,
        emboss = false,
    ),
    bar = PhBar.SOFT,
    card = PhCard.SOFT,
    button = PhButton.SOFT,
    message = PhMessage.QUIET,
    mono = PhMono.SOFT_INSET,
    header = PhHeader.LABEL,
)

object PhThemes {
    val ALL = listOf(GingerbreadTheme, MinimalTheme, TomorrowTheme, StudioTheme)

    fun of(look: PhLook): PhTheme = when (look) {
        PhLook.GINGERBREAD -> GingerbreadTheme
        PhLook.MINIMAL -> MinimalTheme
        PhLook.TOMORROW -> TomorrowTheme
        PhLook.STUDIO -> StudioTheme
    }
}
